# Generated by Django 3.0.8 on 2020-07-09 13:48

import apps.brawler.models
from django.db import migrations, models
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('brawler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brawler',
            name='avatar',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brawler',
            name='cost',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brawler',
            name='description',
            field=models.TextField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brawler',
            name='health',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brawler',
            name='rarity',
            field=django_enumfield.db.fields.EnumField(default=0, enum=apps.brawler.models.Rarity),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brawler',
            name='speed',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
    ]
