# Generated by Django 3.0.8 on 2020-07-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brawler', '0002_auto_20200709_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brawler',
            name='name',
            field=models.CharField(max_length=125, unique=True),
        ),
    ]
