version: "3"

services:
  db:
    image: postgres:13.0
    container_name: brawlerlike_db_1
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file:
      - ./envtest
  backend:
    build: ./backend
    container_name: brawlerlike_backend_1
    command: python manage.py migrate && python manage.py test
    depends_on:
      - db
    env_file:
      - ./envtest


volumes:
  pg_data:
