version: "3"

services:
  db:
    image: postgres:13.0
    volumes:
      - pg_data:/var/lib/postgresql/data/
      - pg_backups:/pg_backups
    env_file:
      - ./envprod
  backend:
    image: docker.pkg.github.com/anthonydeniau/brawlerslike/brawlerslike-backend:release_group_b
    entrypoint:
      - /bin/sh
      - ./entrypoint.sh
    depends_on:
      - db
      - redis
    env_file:
      - ./envprod
    volumes:
      - www:/data/www

  frontend:
    image: docker.pkg.github.com/anthonydeniau/brawlerslike/brawlerslike-frontend:release_group_b
    ports:
      - 80:80
    depends_on:
      - backend
    links:
      - backend
    volumes:
      - www:/data/www

  redis:
    restart: always
    image: redis:6.0.9

  prometheus:
    build: docker.pkg.github.com/anthonydeniau/brawlerslike/brawlerslike-prometheus:release_group_b
    depends_on:
      - backend
    links:
      - backend
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - 9090:9090

volumes:
  pg_data:
  pg_backups:
  www:
