version: "3"

services:
  db:
    image: postgres:13.0
    container_name: brawlerlike_db_1_group_a
    volumes:
      - pg_data:/var/lib/postgresql/data/
      - pg_backups:/pg_backups
    env_file:
      - ./envprod
    expose:
      - "5432"
  backend:
    image: ghcr.io/anthonydeniau/brawlerslike_backend:release_group_a
    container_name: brawlerlike_backend_1_group_a
    entrypoint:
      - /bin/sh
      - ./entrypoint.sh
    expose:
      - "8000"
    depends_on:
      - db
      - redis
    env_file:
      - ./envprod
    volumes:
      - www:/data/www

  nginx:
    image: ghcr.io/anthonydeniau/brawlerslike_nginx:release_group_a
    container_name: brawlerlike_nginx_1_group_a
    ports:
      - 80:80
    depends_on:
      - backend
    links:
      - backend
    volumes:
      - www:/data/www

  redis:
    restart: always
    image: redis:6.0.9
    container_name: brawlerlike_redis_1_group_a

  grafana:
    container_name: brawlerlike_grafana_1_group_a
    image : grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - ./docker/grafana/provisioning:/etc/grafana/provisioning
    env_file:
      - ./envprod
volumes:
  pg_data:
  pg_backups:
  www:
