# Generated by Django 3.0.8 on 2020-07-09 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brawler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileBrawler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('power_points', models.IntegerField()),
                ('brawler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brawler.Brawler')),
            ],
        ),
    ]
