<<<<<<< HEAD
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
        ('userprofilebrawler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilebrawler',
            name='equipments',
            field=models.ManyToManyField(to='equipment.Equipment'),
        ),
    ]
=======
# Generated by Django 3.0.8 on 2020-07-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
        ('userprofilebrawler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilebrawler',
            name='equipments',
            field=models.ManyToManyField(to='equipment.Equipment'),
        ),
    ]
>>>>>>> 2d7299d7c313dea9e53c3106bb9ca4126c19c47b
