# Generated by Django 3.0.8 on 2020-07-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ability', '0003_auto_20200709_1540'),
        ('userprofilebrawler', '0002_userprofilebrawler_equipments'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilebrawler',
            name='abilities',
            field=models.ManyToManyField(to='ability.Ability'),
        ),
    ]
