# Generated by Django 2.2.15 on 2020-08-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('description', models.TextField()),
                ('avatar', models.URLField()),
                ('price', models.IntegerField()),
                ('modelFile', models.URLField()),
                ('textureFile', models.URLField()),
                ('voiceLineFile', models.URLField()),
            ],
        ),
    ]
