# Generated by Django 3.0.8 on 2020-08-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125, unique=True)),
                ('description', models.TextField(max_length=255)),
                ('avatar', models.URLField()),
                ('price', models.IntegerField()),
                ('model_file', models.URLField()),
                ('texture_file', models.URLField()),
                ('voice_line_file', models.URLField()),
            ],
        ),
    ]
