# Generated by Django 3.0.8 on 2020-08-28 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skin',
            old_name='ModelFile',
            new_name='modelFile',
        ),
        migrations.RenameField(
            model_name='skin',
            old_name='TextureFile',
            new_name='textureFile',
        ),
        migrations.RenameField(
            model_name='skin',
            old_name='VoiceLineFile',
            new_name='voiceLineFile',
        ),
    ]
