# Generated by Django 3.0.8 on 2020-08-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skin',
            name='TextureFile',
            field=models.URLField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skin',
            name='ThreeDModelFile',
            field=models.URLField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skin',
            name='VoiceLineFile',
            field=models.URLField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skin',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=5),
            preserve_default=False,
        ),
    ]
