# Generated by Django 3.0.8 on 2020-08-28 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skin', '0002_auto_20200828_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skin',
            old_name='voiceline_file',
            new_name='voice_line_file',
        ),
    ]
