# Generated by Django 3.0.8 on 2020-07-09 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projectilPattern', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectilPattern', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projectilPattern.ProjectilPattern')),
            ],
        ),
    ]
