# Generated by Django 2.2.14 on 2020-07-09 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brawler', '0001_initial'),
        ('ability', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ability',
            name='attackSpeed',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ability',
            name='brawler',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='brawler.Brawler'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ability',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ability',
            name='image',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ability',
            name='isSuper',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ability',
            name='name',
            field=models.CharField(default='', max_length=125),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ability',
            name='reloadSpeed',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
