# Generated by Django 3.0.8 on 2020-07-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ability', '0002_auto_20200709_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='attackSpeed',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='ability',
            name='description',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='ability',
            name='image',
            field=models.URLField(default=' '),
        ),
        migrations.AlterField(
            model_name='ability',
            name='isSuper',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ability',
            name='reloadSpeed',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
    ]
