# Generated by Django 3.0.8 on 2020-08-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ability', '0003_auto_20200709_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='attackSpeed',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='ability',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ability',
            name='image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='ability',
            name='isSuper',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='ability',
            name='reloadSpeed',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
